# plugin.yml
name: CommandBlockServerMover
version: 1.0
main: org.gputest.proxy_command.Proxy_command
api-version: 1.21 # 서버 버전에 맞게 수정하세요 (1.13 이상 권장)
depend: [ ]

commands:
  server:
    description: Velocity 프록시를 통해 플레이어를 다른 서버로 이동시킵니다.
    usage: /server <서버이름>
    permission: commandblockservermover.server # 권한 지정
    permission-message: 이 명령어를 사용할 권한이 없습니다.

permissions:
  commandblockservermover.server:
    description: 커맨드 블록, 콘솔 또는 플레이어가 /server 명령을 사용할 수 있도록 합니다.
    default: op # 기본적으로 OP만 사용 가능하도록 설정 (보안상 권장)